added  data model
BuildForSDG/Team-028-Product pull request #14
Opened 2020-05-12 09:33 UTC by victoryohanna

## Description
Data model is created base on our data schema using Sequelize ORM as earlier agreed.
Controllers and routes are created to test DB connection and CRUD operation carried out for few model on localhost before remote database is setup. 
 
## Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ x] I have added tests that prove my fix is effective and that this feature works
- [x ] New and existing unit tests pass locally with my changes

2020-05-12 15:50 UTC, emydame reviewed
Hi Victor,

Kindly confirm where the database connection is pointing to.

Thanks

2020-05-12 19:18 UTC, Onyedikachi commented
Hi Victor, the recent update to the develop branch produced this conflict. Kindly merge develop branch into the backend-model branch.

Resolve the conflicts and re-push the backend-model branch

2020-05-13 06:05 UTC, Onyedikachi requested changes

2020-05-13 06:05 UTC, Onyedikachi commented on src/backend/model/user.model.js
> +module.exports = (sequelize, Sequelize) => {
Hi victor user model and user categories model are the same

2020-05-13 06:05 UTC, Onyedikachi commented on src/backend/yarn.lock
> +<<<<<<< HEAD
Pls address this line

2020-05-13 06:05 UTC, Onyedikachi commented on src/backend/yarn.lock
> +<<<<<<< HEAD
please address this whole file, you can recreate this file

2020-05-13 11:50 UTC, victoryohanna reviewed
Issues resolved

2020-05-13 13:11 UTC, Onyedikachi approved these changes

2020-05-13 14:41 UTC, Onyedikachi commented
Approved

2020-05-14 08:35 UTC, Onyedikachi commented
Hi Victor, the latest merge to develop produced a new conflict, Kindly resolve

2020-05-14 15:57 UTC, MosesNwaeze commented on src/backend/index.js
> +const PORT = process.env.PORT || 3000;
this port will conflict with the frontend port that runs on 3000

2020-05-14 16:01 UTC, MosesNwaeze approved these changes

2020-05-14 21:49 UTC, emydame approved these changes
Reviewed

2020-05-14 22:54 UTC, emydame commented
Hi Victor, 
Kindly resolve the conflict issue in the yarn file contained in the back-end directory to enable us merge the pull request. It is a versioning conflict and i am not certain which version you might be needing for the backend.

Thank you.

2020-05-15 10:58 UTC, elfizzy approved these changes
Reviewed

2020-05-15 11:01 UTC, emydame commented
This request is closed. Resolution of the conflict shall be handled in another pull request

2020-05-15 11:01 UTC, closed without merging